producerBroker: "localhost:9092"
#producerBroker: "10.19.8.217:9092"
producerTopic: geofil-data
fromHdfs: false
producerSourceFilePath: D:\projects\diplomski\geofil-storm\subscriptions19.json
#producerSourceFilePath: data/publications19.json

consumerAppId: storm-kafka-consumer
consumerClientId: storm-kafka-consumer-client
consumerBroker: "localhost:9092"
#consumerBroker: "10.19.8.217:9092"
#consumerTopic: geofil-data
consumerTopic: geofil-data-storm
consumerDestinationFilePath: test_1.txt
